"""initial schema

Revision ID: 04bf9e46aa79
Revises: 
Create Date: 2026-08-19 22:10:46.394871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04bf9e46aa79'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('starter_code', sa.Text(), nullable=False),
    sa.Column('harness_template', sa.Text(), nullable=False),
    sa.Column('test_case_summary', sa.Text(), nullable=False),
    sa.Column('docs', sa.JSON(), nullable=False),
    sa.Column('reference_solution', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_problems_difficulty'), 'coding_problems', ['difficulty'], unique=False)
    op.create_index(op.f('ix_coding_problems_track'), 'coding_problems', ['track'], unique=False)
    op.create_table('concept_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('model_answer', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_checks_difficulty'), 'concept_checks', ['difficulty'], unique=False)
    op.create_index(op.f('ix_concept_checks_track'), 'concept_checks', ['track'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('choices', sa.JSON(), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_difficulty'), 'quiz_questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_quiz_questions_track'), 'quiz_questions', ['track'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_sub', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('onboarded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_table('days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('track', sa.String(length=32), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('quiz_question_ids', sa.JSON(), nullable=False),
    sa.Column('coding_problem_id', sa.Integer(), nullable=False),
    sa.Column('concept_check_id', sa.Integer(), nullable=False),
    sa.Column('quiz_completed', sa.Boolean(), nullable=False),
    sa.Column('quiz_correct', sa.Integer(), nullable=False),
    sa.Column('quiz_total', sa.Integer(), nullable=False),
    sa.Column('coding_completed', sa.Boolean(), nullable=False),
    sa.Column('coding_attempts', sa.Integer(), nullable=False),
    sa.Column('concept_completed', sa.Boolean(), nullable=False),
    sa.Column('concept_self_rating', sa.Boolean(), nullable=False),
    sa.Column('points_earned', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coding_problem_id'], ['coding_problems.id'], ),
    sa.ForeignKeyConstraint(['concept_check_id'], ['concept_checks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', 'track', name='uq_days_user_date_track')
    )
    op.create_index(op.f('ix_days_date'), 'days', ['date'], unique=False)
    op.create_index(op.f('ix_days_track'), 'days', ['track'], unique=False)
    op.create_index(op.f('ix_days_user_id'), 'days', ['user_id'], unique=False)
    op.create_table('track_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track', sa.String(length=32), nullable=False),
    sa.Column('subscribed_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'track', name='uq_track_subscriptions_user_track')
    )
    op.create_index(op.f('ix_track_subscriptions_track'), 'track_subscriptions', ['track'], unique=False)
    op.create_index(op.f('ix_track_subscriptions_user_id'), 'track_subscriptions', ['user_id'], unique=False)
    op.create_table('code_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('tests_passed', sa.Integer(), nullable=False),
    sa.Column('tests_total', sa.Integer(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['coding_problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_submissions')
    op.drop_index(op.f('ix_track_subscriptions_user_id'), table_name='track_subscriptions')
    op.drop_index(op.f('ix_track_subscriptions_track'), table_name='track_subscriptions')
    op.drop_table('track_subscriptions')
    op.drop_index(op.f('ix_days_user_id'), table_name='days')
    op.drop_index(op.f('ix_days_track'), table_name='days')
    op.drop_index(op.f('ix_days_date'), table_name='days')
    op.drop_table('days')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_quiz_questions_track'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_difficulty'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_concept_checks_track'), table_name='concept_checks')
    op.drop_index(op.f('ix_concept_checks_difficulty'), table_name='concept_checks')
    op.drop_table('concept_checks')
    op.drop_index(op.f('ix_coding_problems_track'), table_name='coding_problems')
    op.drop_index(op.f('ix_coding_problems_difficulty'), table_name='coding_problems')
    op.drop_table('coding_problems')
    # ### end Alembic commands ###
