"""replace coding problems (sandbox) with code review challenges

Revision ID: 8f1c2a4b9d3e
Revises: d878af90e263
Create Date: 2026-08-20 00:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f1c2a4b9d3e'
down_revision: Union[str, None] = 'd878af90e263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('code_review_challenges',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('track', sa.String(length=32), nullable=False),
        sa.Column('difficulty', sa.String(length=16), nullable=False),
        sa.Column('topic', sa.String(length=64), nullable=False),
        sa.Column('title', sa.String(length=128), nullable=False),
        sa.Column('snippet', sa.Text(), nullable=False),
        sa.Column('issues', sa.JSON(), nullable=False),
        sa.Column('distractor_reasons', sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_code_review_challenges_difficulty'), 'code_review_challenges', ['difficulty'], unique=False)
    op.create_index(op.f('ix_code_review_challenges_track'), 'code_review_challenges', ['track'], unique=False)

    # batch_alter_table so this also works on SQLite (used by tests/local dev
    # without DATABASE_URL set) - SQLite can't ALTER constraints in place and
    # needs the copy-and-move strategy batch mode provides; on Postgres this
    # just runs the plain ALTERs directly.
    with op.batch_alter_table('days') as batch_op:
        batch_op.add_column(sa.Column('code_review_challenge_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('code_review_completed', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('code_review_correct', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('code_review_total', sa.Integer(), nullable=False, server_default='0'))

    # Existing Day rows point at a coding_problem_id that's about to stop
    # existing, and this app has no real user data yet (pre-launch, self-
    # hosted) - wipe them rather than trying to backfill a code review
    # challenge that was never actually assigned. get_or_create_day
    # regenerates each one deterministically the next time it's opened.
    op.execute('DELETE FROM code_submissions')
    op.execute('DELETE FROM days')
    op.drop_table('code_submissions')

    # batch mode recreates the whole table from the columns that remain, so
    # the FK referencing coding_problem_id is dropped along with the column
    # itself - no separate drop_constraint call needed (and its autogenerated
    # name isn't reliably known to SQLite's reflection anyway).
    with op.batch_alter_table('days') as batch_op:
        batch_op.drop_column('coding_problem_id')
        batch_op.drop_column('coding_completed')
        batch_op.drop_column('coding_attempts')

    op.drop_index(op.f('ix_coding_problems_difficulty'), table_name='coding_problems')
    op.drop_index(op.f('ix_coding_problems_track'), table_name='coding_problems')
    op.drop_table('coding_problems')

    with op.batch_alter_table('days') as batch_op:
        batch_op.create_foreign_key(
            'days_code_review_challenge_id_fkey', 'code_review_challenges',
            ['code_review_challenge_id'], ['id'],
        )
        batch_op.alter_column('code_review_challenge_id', nullable=False)


def downgrade() -> None:
    raise NotImplementedError("no downgrade path - this migration replaces a content type, not just a schema tweak")
