"""
Seed content for the "System Design" track. Its code review challenges (see
content/code_review_bank.py) live separately, alongside the other tracks',
since they're all the same self-graded shape now.

Pool sizes here (8/8/8/5 per difficulty per content type = 29 each, 87
total) are deliberately deeper than the other two tracks: with easy/medium/
hard each landing on ~8-9 days a month and expert on ~4-5 (see
WEEKDAY_DIFFICULTY), a pool this size gives roughly a month of low-repeat
daily content per difficulty tier.
"""

TRACK = "system_design"

SYSTEM_DESIGN_QUIZ = [
    # ---------------- EASY ----------------
    {
        "difficulty": "easy",
        "topic": "Client-Server Basics",
        "question": "In a typical client-server web architecture, what is the client generally responsible for versus the server?",
        "choices": [
            "The client stores all persistent data; the server only renders UI",
            "The client sends requests and renders responses (e.g. a browser or app); the server processes requests, applies business logic, and manages persistent data",
            "They are interchangeable and either can act as either role",
            "The server only serves static files and never runs any logic",
        ],
        "correct_index": 1,
        "explanation": "This is the standard client/server split: the client owns presentation and user interaction, the server owns business logic and durable state.",
    },
    {
        "difficulty": "easy",
        "topic": "HTTP Basics",
        "question": "What's the main difference between an HTTP GET and a POST request?",
        "choices": [
            "GET is always faster than POST",
            "GET requests are meant to be safe, idempotent reads (parameters typically in the URL, no side effects expected); POST is used to submit data that may create or change state on the server",
            "GET requests cannot include any query parameters",
            "POST requires authentication and GET never does",
        ],
        "correct_index": 1,
        "explanation": "GET is defined as a safe, idempotent method for fetching a representation; POST is the general-purpose 'do something with this data' method, commonly used to create resources.",
    },
    {
        "difficulty": "easy",
        "topic": "Caching Basics",
        "question": "What's the main benefit of adding a cache in front of a database?",
        "choices": [
            "It permanently replaces the need for a database",
            "It serves frequently-requested data from fast memory instead of hitting the slower database every time, reducing latency and database load",
            "It makes every write to the database faster",
            "It guarantees the served data is always perfectly up to date",
        ],
        "correct_index": 1,
        "explanation": "A cache trades a small risk of staleness for much lower read latency and less load on the backing store - it doesn't replace the database, which remains the source of truth.",
    },
    {
        "difficulty": "easy",
        "topic": "Databases",
        "question": "When would you lean toward a NoSQL database (e.g. a document or key-value store) over a traditional relational database?",
        "choices": [
            "Never - relational databases are always the better choice",
            "When your data doesn't fit a rigid schema well, needs to scale horizontally very easily, and you can relax strict relational guarantees (joins, multi-row transactions) for flexibility and throughput",
            "Only when storing images or other binary files",
            "NoSQL databases don't support querying at all, so this never applies",
        ],
        "correct_index": 1,
        "explanation": "The choice is about trade-offs, not superiority: NoSQL stores generally favor flexible schemas and easy horizontal scale over strong relational guarantees like joins and multi-row ACID transactions.",
    },
    {
        "difficulty": "easy",
        "topic": "Load Balancing Basics",
        "question": "What problem does a load balancer solve?",
        "choices": [
            "It encrypts all traffic between client and server",
            "It distributes incoming requests across multiple backend servers so no single server is overwhelmed, and can route around unhealthy instances",
            "It compresses HTTP responses to save bandwidth",
            "It permanently stores session data for every user",
        ],
        "correct_index": 1,
        "explanation": "A load balancer sits in front of a pool of servers and spreads traffic across them (and away from unhealthy ones), which is what makes horizontal scaling actually work end to end.",
    },
    {
        "difficulty": "easy",
        "topic": "Scaling",
        "question": "What's the difference between vertical and horizontal scaling?",
        "choices": [
            "Vertical scaling adds more machines; horizontal scaling adds more power to one machine",
            "Vertical scaling adds more power (CPU/RAM) to a single machine; horizontal scaling adds more machines and distributes load across them",
            "They're two names for the exact same technique",
            "Horizontal scaling only applies to databases, never to application servers",
        ],
        "correct_index": 1,
        "explanation": "Vertical scaling means a bigger box; horizontal scaling means more boxes sharing the load - horizontal scaling is generally preferred at large scale since a single machine has a hard ceiling.",
    },
    {
        "difficulty": "easy",
        "topic": "Latency & Throughput",
        "question": "What's the difference between latency and throughput?",
        "choices": [
            "They're the same metric, just measured with different units",
            "Latency is how long a single request takes to complete; throughput is how many requests a system can handle per unit of time - a system can have low latency but low throughput, or the reverse",
            "Latency only matters for database queries, not for network calls",
            "Throughput is always inversely proportional to the number of servers running",
        ],
        "correct_index": 1,
        "explanation": "Latency measures per-request speed; throughput measures aggregate capacity over time - the two are related but genuinely independent, and systems are often tuned to trade one for the other.",
    },
    {
        "difficulty": "easy",
        "topic": "APIs",
        "question": "In a RESTful API, what does it mean for the API to be 'stateless'?",
        "choices": [
            "The server keeps no memory of the client's state between requests - every request must carry all the information the server needs to process it",
            "The API cannot store any data anywhere, ever",
            "The client is not allowed to send any data to the server",
            "The server processes incoming requests in a random order",
        ],
        "correct_index": 0,
        "explanation": "Statelessness means the server doesn't rely on remembered per-client context between calls; any needed context (auth token, pagination cursor, etc.) travels with each request instead.",
    },
    # ---------------- MEDIUM ----------------
    {
        "difficulty": "medium",
        "topic": "Caching Strategies",
        "question": "In a cache-aside (lazy-loading) caching strategy, what happens on a cache miss?",
        "choices": [
            "The request fails immediately with an error",
            "The application reads from the database, then writes that value into the cache before returning it, so subsequent reads hit the cache",
            "The entire cache is cleared and rebuilt from scratch",
            "The database is bypassed permanently for that key going forward",
        ],
        "correct_index": 1,
        "explanation": "Cache-aside only populates the cache reactively, on demand, when a read actually misses - it never proactively pushes data into the cache.",
    },
    {
        "difficulty": "medium",
        "topic": "Database Indexing",
        "question": "Why does adding a database index speed up reads but slow down writes?",
        "choices": [
            "Indexes only ever affect reads, never writes",
            "An index is an auxiliary sorted structure (e.g. a B-tree) that lets lookups skip a full table scan; every write must also update that structure, adding overhead per insert/update/delete",
            "Indexes make the entire table read-only after creation",
            "There is no real trade-off with adding indexes",
        ],
        "correct_index": 1,
        "explanation": "The index has to stay correct, so every write pays a maintenance cost proportional to how many indexes exist on that table - it's a deliberate read/write trade-off, not a free win.",
    },
    {
        "difficulty": "medium",
        "topic": "Database Replication",
        "question": "In a single-leader (primary-replica) database setup, what's the usual trade-off with asynchronous replication?",
        "choices": [
            "There's no trade-off - it's strictly better in every way",
            "Writes acknowledge as soon as the leader commits, without waiting for replicas, giving lower write latency - but a replica can lag behind, and a failover could lose the most recent writes",
            "It guarantees replicas are always perfectly in sync with the leader",
            "It prevents the leader from ever failing",
        ],
        "correct_index": 1,
        "explanation": "Async replication favors write latency over durability guarantees on replicas - the gap between 'leader has it' and 'replica has it' is exactly the window of possible loss on failover.",
    },
    {
        "difficulty": "medium",
        "topic": "CDN",
        "question": "How does a CDN (content delivery network) reduce latency for users?",
        "choices": [
            "It losslessly compresses all data in transit",
            "It caches content on servers geographically distributed closer to users, so requests are served from a nearby edge location instead of traveling to the origin server",
            "It encrypts all traffic, which is inherently faster than unencrypted traffic",
            "It only works for streaming video content specifically",
        ],
        "correct_index": 1,
        "explanation": "A CDN's core value is proximity: shortening the physical/network distance between the user and the server that answers their request.",
    },
    {
        "difficulty": "medium",
        "topic": "Message Queues",
        "question": "What core problem do message queues solve between a producer service and a consumer service?",
        "choices": [
            "They make each individual service faster on its own",
            "They decouple producers from consumers in time and pace - the producer can publish work without waiting for it to be processed immediately, smoothing traffic spikes and letting each side scale or fail independently",
            "They fully replace the need for a database",
            "They guarantee zero message loss with no configuration required",
        ],
        "correct_index": 1,
        "explanation": "The core value of a queue is decoupling: producers and consumers no longer need to be available, fast, or scaled the same way at the same time.",
    },
    {
        "difficulty": "medium",
        "topic": "Rate Limiting",
        "question": "What is a rate limiter typically protecting a service from?",
        "choices": [
            "Slow disk I/O specifically",
            "Being overwhelmed by too many requests from a client (or in aggregate) in a given time window - whether malicious abuse or an accidental buggy retry loop - by rejecting or throttling requests past a threshold",
            "SQL injection attacks",
            "Data corruption during concurrent writes",
        ],
        "correct_index": 1,
        "explanation": "Rate limiting is about request volume control, protecting shared capacity from any one source (bad actor or bug) consuming more than its fair share.",
    },
    {
        "difficulty": "medium",
        "topic": "Consistent Hashing",
        "question": "Why is consistent hashing preferred over plain modulo hashing (`hash(key) % N`) when distributing keys across a changing set of N servers?",
        "choices": [
            "Consistent hashing is simply faster to compute per key",
            "With plain modulo hashing, adding or removing a server changes N and reshuffles almost every key's target server; consistent hashing arranges servers and keys on a hash ring so only a small fraction of keys need to move when servers change",
            "Modulo hashing cannot be used with string keys",
            "Consistent hashing doesn't require any hash function at all",
        ],
        "correct_index": 1,
        "explanation": "The whole point of consistent hashing is minimizing remapping on membership changes - modulo hashing is maximally disruptive since N appears directly in the formula.",
    },
    {
        "difficulty": "medium",
        "topic": "Database Sharding",
        "question": "What is database sharding, and what's a common challenge it introduces?",
        "choices": [
            "Sharding just means adding an index, and the challenge is slower reads",
            "Sharding splits a dataset across multiple database instances (each holding a subset of rows, by some partition key) to scale beyond a single machine; a common challenge is that queries spanning multiple shards become much harder and slower",
            "Sharding is just another word for replication, with no real difference",
            "Sharding eliminates the need to ever choose a partition key",
        ],
        "correct_index": 1,
        "explanation": "Sharding buys write/storage scale beyond one machine at the cost of cross-shard operations (joins, aggregations, multi-row transactions) becoming distributed problems instead of local ones.",
    },
    # ---------------- HARD ----------------
    {
        "difficulty": "hard",
        "topic": "CAP Theorem",
        "question": "According to the CAP theorem, when a network partition occurs, what must a distributed system choose between?",
        "choices": [
            "Consistency and Availability - it can only guarantee one of the two during the partition, since partition tolerance is treated as a given",
            "Consistency and Durability",
            "Availability and Latency, with Consistency unaffected",
            "Nothing - a well-built system can always guarantee both consistency and availability regardless of partitions",
        ],
        "correct_index": 0,
        "explanation": "CAP says that under an actual network partition (which will happen), you must pick: keep answering (Availability) and risk inconsistency, or refuse to answer inconsistently (Consistency) and lose Availability for affected requests.",
    },
    {
        "difficulty": "hard",
        "topic": "Consistency Models",
        "question": "What does 'eventual consistency' guarantee, and what does it NOT guarantee?",
        "choices": [
            "It guarantees reads always return the latest write immediately",
            "It guarantees that if no new updates are made, all replicas will eventually converge to the same value - but it does NOT guarantee a read immediately after a write will see that write",
            "It guarantees strict global ordering of all writes across all replicas at all times",
            "It's identical to strong consistency, just marketed under a different name",
        ],
        "correct_index": 1,
        "explanation": "Eventual consistency is a convergence guarantee over time, not a freshness guarantee at any given instant - that gap is exactly what trips people up.",
    },
    {
        "difficulty": "hard",
        "topic": "Distributed Transactions",
        "question": "In the Two-Phase Commit (2PC) protocol, what happens in the 'prepare' phase?",
        "choices": [
            "The coordinator immediately commits the transaction on every participant",
            "The coordinator asks every participant whether it can commit; each participant durably persists its intent and votes yes/no, without actually committing yet",
            "All participants automatically roll back",
            "There is no prepare phase in 2PC",
        ],
        "correct_index": 1,
        "explanation": "2PC's whole design is splitting 'can everyone commit?' from 'now actually commit' into two rounds, so the coordinator only tells everyone to commit once it knows all participants are ready.",
    },
    {
        "difficulty": "hard",
        "topic": "Leader Election",
        "question": "Why do distributed systems need a leader election / consensus algorithm (e.g. Raft, Paxos) rather than just picking one server as leader forever?",
        "choices": [
            "Because leaders never actually need to change once chosen",
            "The initial leader can crash or become unreachable, so remaining nodes need an agreed-upon way to detect that and elect a new leader while avoiding two nodes both believing they're the leader at once",
            "Consensus algorithms are used purely for load balancing, not leadership",
            "A single fixed leader is always more available than an elected one",
        ],
        "correct_index": 1,
        "explanation": "Leader election exists specifically to handle failure and avoid a divided cluster where more than one node acts as leader simultaneously - a scenario often called split brain.",
    },
    {
        "difficulty": "hard",
        "topic": "Idempotency",
        "question": "Why does making an API endpoint idempotent matter for handling retries in a distributed system?",
        "choices": [
            "Idempotency makes the endpoint execute faster",
            "If a client times out and doesn't know whether its request succeeded, it can safely retry an idempotent request without risking a double side-effect (e.g. charging a payment twice), since applying it multiple times has the same effect as applying it once",
            "Idempotent endpoints don't require authentication",
            "Idempotency only matters for GET requests",
        ],
        "correct_index": 1,
        "explanation": "Idempotency is what makes 'just retry on timeout' a safe default strategy instead of a source of duplicated side effects.",
    },
    {
        "difficulty": "hard",
        "topic": "Backpressure",
        "question": "What does 'backpressure' mean in a system with a fast producer and a slower consumer, e.g. feeding a queue?",
        "choices": [
            "A mechanism for the consumer (or the layer between them) to signal the producer to slow down, or for excess work to be buffered/dropped deliberately, preventing unbounded queue growth and memory exhaustion",
            "It always means instantly dropping all excess messages with no signal to anyone",
            "It's just another word for load balancing",
            "It only ever applies to database writes",
        ],
        "correct_index": 0,
        "explanation": "Backpressure is a deliberate, controlled response to a rate mismatch, as opposed to letting an unbounded queue silently grow until something crashes.",
    },
    {
        "difficulty": "hard",
        "topic": "Service Discovery",
        "question": "In a microservices architecture where instances scale up/down and get new IPs, what problem does service discovery solve?",
        "choices": [
            "It exists solely to encrypt traffic between services",
            "It lets services find the current network location of other services dynamically, via a registry instances register with/query, instead of relying on hardcoded static addresses that break as instances come and go",
            "It fully replaces the need for load balancers",
            "It's only relevant for client-facing, not internal, traffic",
        ],
        "correct_index": 1,
        "explanation": "Service discovery exists precisely because addresses aren't stable in an elastic environment - it's the mechanism that keeps 'who do I call' accurate as the fleet changes shape.",
    },
    {
        "difficulty": "hard",
        "topic": "Fault Tolerance",
        "question": "What problem does the circuit breaker pattern solve when one service calls another that's failing or slow?",
        "choices": [
            "It automatically repairs the failing downstream service",
            "After detecting repeated failures/timeouts, it 'trips' and fails fast (without even attempting the call) for a cooldown period, preventing the caller from piling up resources waiting on a downstream unlikely to respond, and giving the downstream room to recover",
            "It permanently blocks all calls to any downstream service, forever",
            "It only applies to database calls, never service-to-service calls",
        ],
        "correct_index": 1,
        "explanation": "A circuit breaker converts 'keep trying and waiting on something broken' into 'fail immediately and check back later,' which protects the caller's own resources and gives the downstream breathing room.",
    },
    # ---------------- EXPERT ----------------
    {
        "difficulty": "expert",
        "topic": "Consensus",
        "question": "What is the core guarantee Raft (or Paxos) provides among a cluster of nodes, even if some nodes fail?",
        "choices": [
            "Every node processes requests at exactly the same speed as every other node",
            "All non-faulty nodes agree on the same sequence of values/log entries, in the same order, as long as a majority (quorum) of nodes are up and can communicate",
            "The system tolerates the failure of a majority of nodes and still makes progress",
            "It eliminates the need for any network communication between nodes",
        ],
        "correct_index": 1,
        "explanation": "Consensus algorithms need a majority available to make progress safely, not tolerate a majority failing - safety is preserved (no two nodes disagree on committed entries) even across leader changes, as long as quorum holds.",
    },
    {
        "difficulty": "expert",
        "topic": "Vector Clocks",
        "question": "What problem do vector clocks solve in a distributed system with multiple replicas accepting writes?",
        "choices": [
            "They synchronize physical wall-clock time across all nodes",
            "They let the system detect whether two events (writes) are causally ordered (one happened-before the other) or are truly concurrent/conflicting, without relying on synchronized physical clocks",
            "They compress data during replication",
            "They eliminate the need for any conflict resolution",
        ],
        "correct_index": 1,
        "explanation": "Vector clocks give a logical, causality-aware ordering that survives clock skew between machines - they tell you 'concurrent vs. ordered,' not what time it was.",
    },
    {
        "difficulty": "expert",
        "topic": "CRDTs",
        "question": "What makes a Conflict-free Replicated Data Type (CRDT) useful for multi-region systems accepting writes in multiple regions simultaneously?",
        "choices": [
            "CRDTs prevent any two regions from ever writing at the same moment",
            "CRDTs are designed so concurrent, out-of-order updates from different replicas can always be merged deterministically into the same final state, without needing a coordinator or manual conflict resolution",
            "CRDTs require a single global lock before any write is allowed",
            "CRDTs only work for numeric counter data types",
        ],
        "correct_index": 1,
        "explanation": "The defining property of a CRDT is that its merge function is mathematically guaranteed to converge regardless of the order updates arrive in - that's what removes the need for a coordinator.",
    },
    {
        "difficulty": "expert",
        "topic": "Exactly-Once Delivery",
        "question": "Why is `exactly-once` message delivery across a network considered practically unachievable in the purest sense, and what do real systems do instead?",
        "choices": [
            "It's fully achievable with modern message queues, no caveats needed",
            "A sender can never be 100% sure whether a message was received, since the acknowledgment itself could be lost, so it must choose between risking duplicate delivery or risking loss; real systems typically implement at-least-once delivery plus idempotent/deduplicated processing on the consumer side to achieve an effectively-once outcome",
            "Exactly-once delivery only matters for financial systems",
            "TCP already guarantees exactly-once delivery at the application level",
        ],
        "correct_index": 1,
        "explanation": "The fundamental limit is the ambiguity of a lost acknowledgment - you can't distinguish 'message lost' from 'ack lost' from the sender's side, so systems engineer around it with idempotency rather than eliminating the ambiguity.",
    },
    {
        "difficulty": "expert",
        "topic": "Multi-Region Architecture",
        "question": "What's a key trade-off when deciding whether a multi-region system uses a single 'write region' (others read-only) versus allowing writes in every region?",
        "choices": [
            "There is no trade-off - always allow writes in every region",
            "A single write region keeps writes strongly consistent and simpler, but adds latency for users far from that region and creates a single point of failure for writes; multi-region writes lower write latency locally but require conflict resolution and more complex consistency guarantees",
            "Multi-region writes are always faster and safer than a single write region in every case",
            "This trade-off applies only to caching layers, never to databases",
        ],
        "correct_index": 1,
        "explanation": "This is a direct instance of the consistency/latency/complexity trade-off that recurs throughout distributed systems design - there's no universally correct answer, only the right one for the specific data and access pattern.",
    },
]

SYSTEM_DESIGN_CONCEPT = [
    # ---------------- EASY ----------------
    {
        "difficulty": "easy",
        "topic": "Scalability",
        "prompt": "In your own words, what does it mean for a system to 'scale', and why can't you just keep making one server bigger forever?",
        "model_answer": "Scaling means a system can handle more load - more users, requests, or data - without falling over or becoming unacceptably slow. Vertical scaling (making one server bigger) hits real limits: there's a maximum CPU/RAM/disk you can put in a single machine, it gets disproportionately expensive at the high end, and it's a single point of failure - if that one machine dies, everything is down. Horizontal scaling (adding more machines and distributing load across them) avoids the hard ceiling and adds redundancy, which is why most large systems eventually scale out rather than just up.",
    },
    {
        "difficulty": "easy",
        "topic": "Caching",
        "prompt": "What is a cache, and what's the core risk you take on by adding one?",
        "model_answer": "A cache is a smaller, faster storage layer that keeps a copy of frequently-accessed data so future requests can be served without going to the slower source of truth, like a database. The core risk is staleness: the cached copy can drift out of sync with the real data after it changes, so you need a deliberate invalidation or expiration strategy (TTLs, explicit invalidation on writes, etc.) - a cache that's never invalidated is really just a source of stale-data bugs waiting to happen.",
    },
    {
        "difficulty": "easy",
        "topic": "HTTP",
        "prompt": "Explain what an HTTP status code communicates, and give one example each of a 2xx, 4xx, and 5xx code with what it means.",
        "model_answer": "HTTP status codes tell the client the outcome category of its request. 2xx means success - e.g. 200 OK, the request succeeded and here's the result. 4xx means the client did something the server considers wrong - e.g. 404 Not Found, the requested resource doesn't exist. 5xx means the server itself failed to fulfill an otherwise valid request - e.g. 500 Internal Server Error, something broke on the server's side. The category (the first digit) lets clients and monitoring react generically even without knowing every specific code.",
    },
    {
        "difficulty": "easy",
        "topic": "Databases",
        "prompt": "What is a primary key, and why does almost every database table need one?",
        "model_answer": "A primary key is a column (or set of columns) that uniquely identifies each row in a table - no two rows can share the same primary key value. It matters because it gives every row a stable, unique handle: other tables reference rows via foreign keys pointing at the primary key, indexes are commonly built on it for fast lookups, and without one there'd be no reliable way to say 'update or delete exactly this row' if other columns could contain duplicates.",
    },
    {
        "difficulty": "easy",
        "topic": "Networking Basics",
        "prompt": "What does DNS do, in plain terms, when you type a website's domain name into a browser?",
        "model_answer": "DNS (the Domain Name System) translates a human-readable domain name, like example.com, into the numeric IP address a computer actually needs to open a network connection. The browser asks a DNS resolver to look up the domain, which - possibly after checking several layers of nameservers - returns an IP address; the browser then connects to that IP to actually request the page. It's essentially the internet's phonebook.",
    },
    {
        "difficulty": "easy",
        "topic": "Statelessness",
        "prompt": "Why do most scalable web APIs try to be 'stateless' between requests, rather than having the server remember things about a specific client's session in its own memory?",
        "model_answer": "If a server keeps client-specific state, like a shopping cart, only in its own memory, then that client's future requests must always hit that exact same server or the data appears to vanish. That breaks horizontal scaling and load balancing, since a load balancer wants to freely route any request to any healthy instance. Statelessness - with any needed state stored externally, e.g. in a shared database or cache, or passed by the client itself like a token - lets any server instance handle any request, which is what actually makes adding and removing instances and load-balancing work.",
    },
    {
        "difficulty": "easy",
        "topic": "Redundancy",
        "prompt": "What does 'single point of failure' mean, and how do systems typically address one?",
        "model_answer": "A single point of failure is any one component whose failure takes down the whole system, even if everything else is healthy - e.g. one server, one database instance, one network link. Systems address this with redundancy: running multiple instances of that component, like multiple app servers behind a load balancer, or a database with replicas that can be promoted, so the failure of any single instance causes at most a reduced-capacity or automatically-recovered state instead of a full outage.",
    },
    {
        "difficulty": "easy",
        "topic": "APIs",
        "prompt": "What's the difference between an API's 'contract' and its implementation, and why does that distinction matter when a team wants to change how an endpoint works internally?",
        "model_answer": "The contract is the externally visible interface - the request/response shape, status codes, and behavior that callers depend on; the implementation is the internal code, logic, and data model behind it, which is free to change as long as the contract stays the same. This matters because it lets a team refactor, optimize, or even rewrite an endpoint's internals - swap the underlying database, change the algorithm - without breaking any client, as long as they don't change the contract; versioning is only needed when the contract itself must change.",
    },
    # ---------------- MEDIUM ----------------
    {
        "difficulty": "medium",
        "topic": "Caching Strategies",
        "prompt": "Compare cache-aside and write-through caching: what's the practical difference in how data gets into the cache, and what's a downside of each?",
        "model_answer": "Cache-aside (lazy loading): the app checks the cache first; on a miss it reads from the database and populates the cache. Downside: the first request for any key is always slow (a guaranteed miss), and if writes don't also invalidate the cache, stale data can linger. Write-through: every write goes through the cache, which updates itself and the database together, so the cache is always warm and consistent with the database on the write path. Downside: every write pays extra cache-write latency, and data that's never actually read still gets cached, wasting cache space, unlike cache-aside which only caches what's genuinely requested.",
    },
    {
        "difficulty": "medium",
        "topic": "Replication",
        "prompt": "What is replication lag, and what real user-facing problem can it cause?",
        "model_answer": "Replication lag is the delay between a write landing on the primary database and that same write showing up on a replica. It can cause a read-your-own-write problem: if a user submits a change and the app immediately reads it back from a replica that hasn't caught up yet, the user sees their own update appear to have not happened - or even reverted - which is confusing and looks like a bug even though the write actually succeeded.",
    },
    {
        "difficulty": "medium",
        "topic": "Load Balancing",
        "prompt": "What's the difference between a Layer 4 (transport-level) and Layer 7 (application-level) load balancer, and what extra capability does Layer 7 give you?",
        "model_answer": "A Layer 4 load balancer routes based only on network/transport info - IP address and port - without looking at the actual HTTP request content, which makes it fast and simple but blind to what's being requested. A Layer 7 load balancer inspects the actual HTTP request - headers, path, cookies - and can route based on it, e.g. sending /api/* to one backend pool and /static/* to another, doing content-based routing, or making smarter session-affinity decisions - at the cost of doing more work per request.",
    },
    {
        "difficulty": "medium",
        "topic": "Message Queues",
        "prompt": "What does 'at-least-once' delivery from a message queue mean for consumers, and what does that force the consumer to handle?",
        "model_answer": "At-least-once delivery means the queue guarantees a message will be delivered one or more times - it may occasionally deliver the same message twice, e.g. if an acknowledgment is lost after processing but before the queue records it, but it will never silently drop a message. This forces consumers to be idempotent: processing the same message twice must produce the same end result as processing it once, typically by tracking already-processed message IDs, or duplicate side effects like double-charging a customer can occur.",
    },
    {
        "difficulty": "medium",
        "topic": "Rate Limiting",
        "prompt": "Compare the token bucket and fixed window counter approaches to rate limiting - what's the main weakness of a naive fixed window, and how does token bucket avoid it?",
        "model_answer": "A fixed window counter resets a counter every window, e.g. every 60 seconds, and rejects requests once the count hits the limit within that window. Its weakness: a client can burst up to the limit right at the end of one window and again right at the start of the next, getting nearly twice the intended rate in a short span straddling the boundary. Token bucket instead has tokens refill continuously, or in small increments, at a steady rate up to a max bucket size, and each request consumes a token - this smooths the allowed rate out over time and avoids the sharp boundary-effect burst that fixed windows allow.",
    },
    {
        "difficulty": "medium",
        "topic": "Database Indexing",
        "prompt": "Why doesn't it make sense to just add an index on every column of every table?",
        "model_answer": "Every index has to be updated on every insert, update, or delete that touches its column(s), so more indexes mean slower writes and more storage used, even for indexes that are rarely or never actually used by real queries. Indexes are a targeted trade-off - you add them for columns frequently filtered, sorted, or joined on in real query patterns, and skip them elsewhere; a table with an index on every column pays the write cost of all of them for the query benefit of only a few.",
    },
    {
        "difficulty": "medium",
        "topic": "CDN",
        "prompt": "Static assets, like a JS bundle, are usually fine to cache aggressively in a CDN, but a personalized API response, like a user's dashboard data, usually isn't. Why the difference?",
        "model_answer": "Static assets are identical for every user and only change on deploy, so caching them for a long time - often with a versioned or hashed filename so a new deploy gets a new URL - is both safe and highly effective. A personalized API response differs per user and can change frequently based on their own actions, so caching it at a shared CDN edge risks serving one user's data to another, or serving stale data right after their own action - it needs either no caching, very short caching, or cache keys that fully incorporate the user's identity plus invalidation on relevant writes.",
    },
    {
        "difficulty": "medium",
        "topic": "Sharding",
        "prompt": "What is a 'hot shard', and give an example of a shard key choice that would cause one.",
        "model_answer": "A hot shard is a shard that receives disproportionately more traffic or load than the others, becoming a bottleneck even though the overall system has plenty of total capacity spread across shards. Example: sharding a multi-tenant system by signup date instead of tenant id would put every newly active or growing tenant's data on the most recent shard, concentrating almost all current write and read traffic there while older shards sit idle - a bad shard key can make horizontal scaling not actually help.",
    },
    # ---------------- HARD ----------------
    {
        "difficulty": "hard",
        "topic": "CAP Theorem",
        "prompt": "A teammate says 'we chose to be CP instead of AP.' Explain in plain terms what trade-off they made and give a scenario where that choice makes sense.",
        "model_answer": "Choosing CP - Consistent and Partition-tolerant, sacrificing Availability during a partition - means that during a network partition, the system will refuse some requests, returning an error or becoming unavailable to some clients, rather than risk returning inconsistent or stale data. This makes sense for something like a system managing account balances or inventory counts, where serving incorrect data - e.g. letting two nodes both think there's one item left in stock and both sell it - is worse than temporarily refusing service until the partition heals and the nodes can agree again.",
    },
    {
        "difficulty": "hard",
        "topic": "Consistency Models",
        "prompt": "What's the difference between 'strong consistency' and 'read-your-own-writes' consistency, and why might a system offer the weaker read-your-own-writes guarantee instead of full strong consistency?",
        "model_answer": "Strong consistency guarantees every reader, everywhere, sees the most recent write immediately after it completes - the strictest and most expensive guarantee to provide at scale. Read-your-own-writes is weaker: it only guarantees that the specific user who made a write will see their own write on subsequent reads, e.g. by routing their reads to the primary or a replica known to be caught up, while other users might briefly see stale data. Systems offer the weaker guarantee because it solves the most common user-facing pain - seeing your own action seemingly not take effect - while still allowing cheaper, eventually-consistent replication for reads from everyone else, a pragmatic middle ground.",
    },
    {
        "difficulty": "hard",
        "topic": "Distributed Transactions",
        "prompt": "Why is the Saga pattern often preferred over Two-Phase Commit for transactions spanning independently-owned microservices?",
        "model_answer": "Two-phase commit requires a coordinator to hold locks across all participants while waiting for every participant to vote, which means all involved services must be available and responsive at the same time, and a stalled coordinator or participant can leave others blocked holding locks - poor availability and tight coupling. Sagas instead break the transaction into a sequence of independent local transactions, each service committing its own step immediately and publishing an event, with compensating actions defined to undo earlier steps if a later step fails - trading strict atomicity for availability and loose coupling, which fits better when services are owned by different teams and databases and can't share a transaction coordinator.",
    },
    {
        "difficulty": "hard",
        "topic": "Fault Tolerance",
        "prompt": "What's the difference between a retry with exponential backoff and a circuit breaker, and why do systems often use both together rather than just retries alone?",
        "model_answer": "Retrying with exponential backoff handles transient failures - a single request failing - by waiting increasingly longer between attempts, giving a temporarily-struggling downstream time to recover. A circuit breaker instead tracks failure patterns over many requests and, once a downstream looks persistently unhealthy, stops sending requests to it entirely for a cooldown period. Using retries alone against a downed downstream just means every caller keeps hammering it with retries, making recovery harder and wasting caller resources waiting; pairing retries for occasional blips with a circuit breaker for sustained outages gets the best of both - resilience to brief hiccups without amplifying a real outage.",
    },
    {
        "difficulty": "hard",
        "topic": "Idempotency",
        "prompt": "Explain why idempotency has to be enforced server-side, via something like a stored idempotency key, rather than just relying on the client to not click submit twice.",
        "model_answer": "Client-side prevention, like disabling a button after click, only prevents the easy accidental case, and doesn't protect against the actual hard case: the client genuinely doesn't know if its request succeeded, e.g. it timed out waiting for a response, and correctly decides to retry - that's not user error, it's the client behaving correctly under uncertainty. Only the server can definitively know whether it has already processed this exact logical operation, so it needs to durably record the outcome of each idempotency-keyed operation and short-circuit any duplicate carrying the same key, regardless of why the duplicate arrived.",
    },
    {
        "difficulty": "hard",
        "topic": "Backpressure",
        "prompt": "If you just let an unbounded queue grow instead of implementing backpressure, what eventually breaks, and why is 'no backpressure' not actually a neutral or safe default?",
        "model_answer": "An unbounded queue absorbing a sustained rate mismatch, producer faster than consumer, will keep growing until it exhausts memory on whatever's hosting it, at which point that process crashes - taking down in-flight work and potentially the whole node, a much worse failure mode than gracefully rejecting or shedding some excess load earlier. 'No backpressure' isn't neutral because it just delays and worsens the failure - it converts a controllable, visible problem, like a queue-depth alarm and some rejected requests, into an uncontrolled one, like an out-of-memory crash and cascading failure to whatever else shares that resource.",
    },
    {
        "difficulty": "hard",
        "topic": "Service Discovery",
        "prompt": "In a service-discovery setup, what happens if an unhealthy instance isn't promptly removed from the registry, and what mechanism keeps the registry accurate?",
        "model_answer": "If a dead or unhealthy instance stays listed, some fraction of requests routed to it will fail or time out even though enough healthy capacity exists elsewhere, and clients or load balancers keep wasting time trying it. Registries stay accurate via health checks: instances either send periodic heartbeats to the registry and are removed if a heartbeat is missed for too long, or the registry or load balancer actively polls a health endpoint on each instance, removing any that fail checks - so routing decisions are based on currently-healthy instances rather than a stale membership list.",
    },
    {
        "difficulty": "hard",
        "topic": "Multi-Region",
        "prompt": "Why is 'just deploy to multiple regions' not sufficient by itself to get real high availability, and what else has to be designed deliberately?",
        "model_answer": "Simply running copies of an app in multiple regions doesn't help if they all depend on one region's database, one region's DNS or traffic-routing decision, or share some other single point of failure - the app is multi-region in name but still has a hidden single point of failure. Real multi-region availability requires deliberately replicating the data layer across regions with a defined consistency or conflict strategy, a traffic-routing or failover mechanism that can detect a region is down and redirect users elsewhere, and actually testing that failover works - regions silently diverging or failover paths that were never exercised are common causes of multi-region setups failing exactly when needed.",
    },
    # ---------------- EXPERT ----------------
    {
        "difficulty": "expert",
        "topic": "Trade-off Analysis",
        "prompt": "A team wants to migrate a monolith to microservices purely because 'microservices scale better.' What's misleading about that framing, and what do microservices actually trade for what?",
        "model_answer": "A well-designed monolith can scale horizontally too, running many stateless instances behind a load balancer, so the framing that scaling requires microservices isn't accurate. What microservices actually trade for is independent deployability and independent scaling of specific components - you can scale just the hot service instead of everything - plus team autonomy, since different teams can own different services. The cost is massively more operational complexity: network calls where there used to be function calls, distributed transactions or sagas instead of local ACID transactions, service discovery, and harder debugging since a single request now spans multiple services and logs. It's a real trade, not a free scaling upgrade - teams should migrate for the specific problems microservices solve, not for scaling in the abstract.",
    },
    {
        "difficulty": "expert",
        "topic": "Consistency vs. Availability",
        "prompt": "Explain, with a concrete example, why 'availability' and 'uptime' are not quite the same thing in a distributed system that has chosen to be CP during partitions.",
        "model_answer": "A CP system can have 100% of its nodes technically up and running, high uptime in the infrastructure sense, while still refusing to serve some requests during a network partition, because it's deliberately choosing to be unavailable to preserve consistency rather than risk a wrong answer. So a monitoring dashboard showing all instances healthy can coexist with real user-facing unavailability, errors or timeouts, during a partition - uptime measures whether processes are running, availability measures whether the system is successfully serving requests, and a CP system can sacrifice the latter while the former stays green.",
    },
    {
        "difficulty": "expert",
        "topic": "Caching at Scale",
        "prompt": "What is 'cache stampede', also known as thundering herd, and describe one technique to prevent it?",
        "model_answer": "Cache stampede happens when a popular cached key expires, or the cache is cold-started, and a large burst of concurrent requests all miss the cache at the same instant, then all independently hammer the backing database or service to recompute the same value simultaneously, potentially overwhelming it right when it's already under load. A common mitigation is a locking or single-flight approach: when a miss occurs, only the first request actually goes to the database to recompute the value, acquiring a short-lived lock for that key, while concurrent requests for the same key either wait for that result or briefly serve a slightly-stale value, instead of all of them independently hitting the backend.",
    },
    {
        "difficulty": "expert",
        "topic": "Data Modeling at Scale",
        "prompt": "Why do large-scale systems often deliberately denormalize data, duplicating it across places, even though it violates classic relational-database normalization principles?",
        "model_answer": "Normalization minimizes redundancy and update anomalies, which is great for correctness and storage efficiency at moderate scale, but it usually requires joins across normalized tables to answer real queries, and joins get expensive and hard to shard as data and query volume grow, especially across sharded or distributed data stores where a join might mean cross-network calls. Denormalization trades some storage and write complexity - the same fact now lives in multiple places and must be kept in sync, e.g. via events - for read performance and shardability. It's an intentional trade favoring the read-heavy, horizontally-scaled access patterns that dominate at large scale, not a mistake.",
    },
    {
        "difficulty": "expert",
        "topic": "Observability at Scale",
        "prompt": "In a system of dozens of microservices, why do logs and metrics alone often fail to answer 'why was this one request slow', and what capability fills that gap?",
        "model_answer": "A single user request in a microservices system can fan out across many services, each with its own logs and metrics showing only that service's own isolated view - there's no built-in way to see the whole path one specific request took or which of the many hops was the actual bottleneck. Distributed tracing fills this gap: each request is tagged with a shared trace id propagated through every service call it touches, and each service reports timed spans against that trace id, so all the pieces can be reassembled into one end-to-end timeline showing exactly which hop or hops accounted for the latency.",
    },
]
